- .eslintrc.json
- package.json
- pages/_document.tsx
- pnpm-lock.yaml
78d4b3da0febf264b1c9ea2b90e7cc2ad5dabe6b 린트 처리를 위한 라이브러리 추가
03e6f61c1c456368feaf1a0e4d7fb8ac750a40a2 린트 설정
1차적으로 린트 작업은 이렇게 마무리합니다. 이후에 추가될 필요가 있는 린트들은 작업 중에 함께 추가해나가면 좋을 것 같습니다!
개인적인 선호로 추가한 린트룰도 있어서 혹시 이견이 있으시다면 커멘트 부탁드립니다!
> [Feature/BAR-3] 린트 룰 설정

- .github/CODEOWNERS
- .storybook/main.ts
- .storybook/preview.ts
- package.json
- pnpm-lock.yaml
- `root/.stories/main.ts`에서 storie 파일의 위치를 확인해주세요
> [Feature/BAR-5] 스토리북 패키지 추가

- .dockerignore
- .github/workflows/deploy.yaml
- Dockerfile
- pages/index.tsx
https://ba-ro.co.kr 배포 완료하였습니다.
말씀해주셨던 pm2의 부하 문제는 확인해보기 전이지만, 원래도 도커를 사용하는 형태가 더 좋을 것 같다고 생각이 들어서 진행해보았습니다. pm2 관련해서는 추가적으로 확인해보도록 하겠습니다.
베포 과정을 문서화 할 계획인데 이때 pm2에 대한 내용도 추가해보겠습니다.
현재 배포는 `feature/deploy-test` 브랜치 기준으로 되어 있습니다.
> 머지 이후 cd workflow 정상 동작에 대한 확인이 필요합니다.
> [Feature/BAR-13] FE 배포

- .eslintrc.json
- package.json
- pages/_app.tsx
- pnpm-lock.yaml
- src/components/Providers/TanstackQueryProvider.tsx
- TanstackQueryProvider 컴포넌트를 생성해 `@tanstack/react-query`와 관련된 설정들을 모두 분리했습니다.
- `defaultOptions` 중 추가하고 싶은 옵션이 있다면 코멘트 남겨주세요.
- `@tanstack/eslint-plugin-query`에 관한 내용은 [요기](https://tanstack.com/query/v5/docs/react/eslint/eslint-plugin-query)를 참고해주세요.
> [Feature/BAR-7] @tanstack/react-query 설정

- package.json
- pnpm-lock.yaml
- src/components/Modal/stores/modalStore.ts
`createPortal`을 사용할 예정입니다. 하지만 `createPortal`만을 사용하는 경우 컴포넌트 외부에서 팝업을 여는 코드 작성이 어려워 `zustand`와 함께 작성할 계획입니다.
```javascript
const ModalContainer = () => {
const modalData = useModalStore((state) => state.modalData)
if (!modalData.title) return null
return createPortal(
<Modal title={title} ... />,
document.getElementById("modal-root") as HTMLDivElement
)
}
```
다음과 같은 형태가 될 것으로 생각하고 있습니다.
제가 17~19일 2박 3일로 여행을 좀 다녀올 예정입니다. 너무 늦게 말씀드려서 죄송합니다 ㅠㅠ
그래서 다음주부터 하기로 이야기했던 디스코드 코어타임은 수요일부터 참가가 가능할 것 같습니다.
화요일 늦은 밤에 보통 진행하였던 저희끼리의 회의에도 참여할 수 있을 것 같습니다만, 오늘 내일 리뷰 속도는 엄청 느리거나 하지 못 할 것 같습니다. 2틀 동안은 원진님이나 은지님의 approve만으로도 머지해도 좋을 것 같습니다.
zustand 사용 관련 피드백 부탁드립니다.
모달을 띄우는 다른 좋은 방법이 있다면 제안 부탁드립니다.
> [Feature/BAR-38] zustand 기본 세팅

- src/components/Button/Button.stories.tsx
- src/components/Button/index.tsx
- src/components/Button/style.css.ts
모달쪽 버튼은 모달 액션 가이드 반영시 수정하겠습니다.
> 스토리북에 버튼이 정상 노출되어야 합니다.
> [Feature/BAR-156] 버튼 컴포넌트 작성

- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/constants.ts
- src/components/Badge/style.css.ts
- src/styles/tokens.ts
> [Feature/BAR-89] Badge 컴포넌트 구현

- src/api/http.ts
- 각자 쓰시는 hoc나 인스턴스를 공유주시면 좋을것 같습니다. https://github.com/YAPP-Github/23rd-Web-Team-2-FE/discussions/28#discussion-6036945
> [Feature/BAR-172] API 레이어 구현

- src/api/http.ts
> [Feature/BAR-172] API 레이어 구현 (Restored)

- package.json
- pnpm-lock.yaml
- `@storybook/addon-onboarding` 패키지는 더 이상 불필요할 것 같아 제거했어요.
- 해당 브랜치에서 확인해주세요!
> [Chore/BAR-189] @tanstack/react-query, @tanstack/react-query-devtools peer dependency 오류 해결

- .github/workflows/deploy.yaml
- src/api/http.ts
- src/components/Button/index.tsx
- src/components/Input/WriteInput/index.tsx
- src/components/Portal/index.tsx
- src/components/Tooltip/TooltipContent.tsx
`strict: true` 선언으로 인해 발생하는 타입 에러들을 수정합니다.
https://github.com/aws-actions
aws-actions를 사용합니다.
ECR에 저장하는 도커 이미지는 최신 5개만으로 유지합니다.
EC2 환경에서는 현재 구동 중인 도커 이미지만을 남깁니다.
- `pnpm build` 시 성공해야 합니다.
- 배포에 성공해야 합니다.
> [Feature/BAR-140] 기존 도커 이미지 삭제 및 빌드 실패 해결

- .husky/pre-commit
이전에 말씀주셨던 내용이 no-stash 제거 정도의 이야기였을까요?
일단 no-stash 옵션이 있는 경우 파일의 부분 커밋이 불가능하여, 제거하였습니다.
> pre-commit lint stage 동작 확인
> [Feature/BAR-202] no-stash 옵션 제거

- commitlint.config.js
기존에 lower-case만 작성가능 했지만 아래 케이스들 모두 가능하도록 수정해두었습니다.
```
[
'lower-case', // default
'upper-case', // UPPERCASE
'camel-case', // camelCase
'kebab-case', // kebab-case
'pascal-case', // PascalCase
'sentence-case', // Sentence case
'snake-case', // snake_case
'start-case', // Start Case
];
```
> [Chore/BAR-215]: commitlint의 기본 subject-case rule 제거

- .storybook/preview-body.html
- src/components/Toast/Toast.stories.tsx
- src/components/Toast/index.tsx
- src/components/Toast/style.css.ts
- src/constants/portal.ts
- src/constants/toast.ts
- src/stores/toast.ts
- 스토리북의 토스트가 정상 동작해야합니다.
- 토스트가 사용되지 않는 경우 토스트 관련 div 태그는 제거되어야 합니다.
> [Feature/BAR-203] 토스트 지속 노출 제거 및 가이드 반영

- .github/workflows/deploy.yaml
https://github.com/YAPP-Github/23rd-Web-Team-2-FE/actions/runs/7783894453
> actions에 warning 메시지 노출되면 안됩니다.
> [Feature/BAR-230] github checkout version up

- package.json
- pnpm-lock.yaml
- `<Link>`, `Router`를 사용해 페이지 전환시 CSS 파일이 불러오지 않는 문제가 있었고, 실제 [이슈](https://github.com/vanilla-extract-css/vanilla-extract/issues/1152)에도 올라와있는 사항이었습니다.
> [Fix/BAR-232] 페이지 전환시 CSS 파일이 생성되지 않는 문제 해결

- src/domain/계정설정/components/Form/index.tsx
> [feature/BAR-234] 아이콘 경로 오류 해결

- src/components/Modal/index.tsx
좋은 방법은 아니지만.... 가장 빠른 방법이라 이렇게 적용해보았습니다!
- 모달 노출시 스크롤이 불가능해야 합니다.
> [Bug/BAR-240] 모달 노출시 스크롤 블락

- src/components/Layout/components/Footer.tsx
- src/components/Layout/index.tsx
- src/components/Layout/style.css.ts
- src/domain/landing/index.tsx
- src/domain/landing/style.css.ts
> [Feature/Bar-247] 랜딩 페이지 CSS 수정

- middleware.ts
- pages/main/index.tsx
- pages/redirect/[authType]/index.tsx
- src/components/Layout/MainPageTab.tsx
- src/components/Layout/components/Header.tsx
- src/domain/저장하는/components/NotFoundArchiveCard/index.tsx
- 저장하는 페이지에서 버튼 클릭시 참고하는 탭 이동 확인
- 기존 메인페이지로 이동하는 동선에서 정상 동작 확인
> [Fix/BAR-252] 메인 페이지의 type searchParam에 저장

- pages/api/spell-check.ts
> [Fix/BAR-259] 특수문자가 포함된 문장의 맞춤법 검사 오류 해결

- pages/main/index.tsx
- pages/profile/index.tsx
- src/api/http.ts
- src/domain/계정설정/components/ExitModal/index.tsx
- src/domain/계정설정/components/Form/index.tsx
- src/domain/계정설정/mutations/useExitAccount.ts
- src/domain/계정설정/queries/useGetProfile.ts
> [Fix/BAR-270] 계정설정 페이지 연동

- src/components/Layout/components/Header.tsx
> [Fix/BAR-266] 약관 페이지 헤더 수정

- src/domain/참고하는/components/FilterButtons.css.ts
https://www.notion.so/ssarivibebe/QA-7c2a91d868ed43ea9ddf90da32695c22?pvs=4#95cc287665784e7ba081094c79328e3d
참고하는 탭에서 호버 혹은 활성화 시에만 shadow가 노출되어야 합니다.
> [Fix/BAR-247] 참고하는 탭 boxShadow 조건부 노출

- src/domain/참고하는/components/참고하는TemplateCard.css.ts
https://www.notion.so/ssarivibebe/QA-7c2a91d868ed43ea9ddf90da32695c22?pvs=4#c26bba973d294bad82b9bbe85d089d48
참고하는 템플릿 호버시 box shadow 노출되어야 합니다.
> [Fix/BAR-275] 참고하는 탬플릿 호버시 box shadow 노출

- pages/profile/index.tsx
- src/components/Layout/components/ProfileButton.tsx
- src/components/Layout/style.css.ts
- src/domain/계정설정/components/Form/index.tsx
- src/domain/계정설정/index.css.ts
- src/domain/계정설정/mutations/useUpdateProfile.ts
이미지쪽 이슈가 아직 있는데 이 부분은 서버분들이랑도 같이 볼게요!
> [Feature/BAR-279] 계정설정 이슈 해결

- package.json
- pages/_document.tsx
- pnpm-lock.yaml
https://wit.nts-corp.com/2024/02/06/6879
overlay scrollbar에 대한 내용은 이곳에 잘 정리되어 있습니다!
- 끄적이는, 참고하는 탭 전환시 스크롤바로 인해 화면의 크기가 변동되어서는 안됩니다.
> [Fix/BAR-278] overlay scrollbar 적용

- src/components/Dropdown/components/DropdownTitle.tsx
- src/components/Layout/components/ProfileButton.tsx
- src/components/Layout/style.css.ts
> [Fix/BAR-280] 프로필 네임 좌측 정렬

- src/components/Layout/style.css.ts
- src/domain/끄적이는/components/WriteTabContent/style.css.ts
> [Feature/BAR-281] 입력창, 탭 배경색 변경

- .github/CODEOWNERS
- src/components/Tabs/components/TabsTrigger.tsx
- src/components/Tabs/style.css.ts
- tab이 active 상태일 때 스타일이 깨지는 문제를 수정했어요.
> [Fix/BAR-282] Switcher Tab active 애니메이션 수정

- pages/_app.tsx
> [Chore/BAR-284] Google Tag Manager 설정
